#pragma once

#define ICON_FK_ARROW_DOWN "Down"
#define ICON_FK_ARROW_LEFT "Left"
#define ICON_FK_ARROW_RIGHT "Right"
#define ICON_FK_ARROW_UP "Up"
#define ICON_FK_BAN "Mute"
#define ICON_FK_BATTERY_EMPTY "Bat 0"
#define ICON_FK_BATTERY_FULL "Bat 4"
#define ICON_FK_BATTERY_HALF "Bat 2"
#define ICON_FK_BATTERY_QUARTER "Bat 1"
#define ICON_FK_BATTERY_THREE_QUARTERS "Bat 3"
#define ICON_FK_COG "Settings"
#define ICON_FK_EXCLAMATION_CIRCLE "!"
#define ICON_FK_EYE "Show"
#define ICON_FK_FILE_IMAGE_O "Image"
#define ICON_FK_FLOPPY_O "Save"
#define ICON_FK_INFO_CIRCLE "Info"
#define ICON_FK_LIB_TESTPATTERN "Test"
#define ICON_FK_LINE_CHART "Diag"
#define ICON_FK_LOCK "Lock"
#define ICON_FK_MINUS_CIRCLE "-"
#define ICON_FK_OBJECT_UNGROUP "Zones"
#define ICON_FK_PAUSE "Pause"
#define ICON_FK_PENCIL "Edit"
#define ICON_FK_PLUG "Plug"
#define ICON_FK_PLUS_CIRCLE "+"
#define ICON_FK_PLUS_SQUARE "+"
#define ICON_FK_QUESTION_CIRCLE "?"
#define ICON_FK_SIGN_OUT "Fit"
#define ICON_FK_TH "Grid"
#define ICON_FK_TIMES "X"
#define ICON_FK_UNDO "Reset"
