name: build-ios-tvos

# make the action not run on the local repo if the branch is also in a pull request to OF/OF
on: [push]

env:
  ccache: ccache

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-ios-tvos:
    runs-on: macos-13
    strategy:
        matrix:
          cfg:
          - {target: ios, libs: ios}
          #- {target: tvos, libs: ios} #broken currently maybe better to just remove
    env:
     TARGET: ${{matrix.cfg.target}}
    steps:
    - name: checkout openframeworks
      uses: actions/checkout@v4
      with:
        repository: openframeworks/openFrameworks
    # now we add in ofxLaser as addon
    - name: checkout ofxLaser
      uses: actions/checkout@v4
      with:
        path: ${{ github.workspace }}/addons/ofxLaser
    # and here we replace the empty example with the hello laser example
    - name: remove emptyExample
      run: rm -r ${{ github.workspace }}/examples/templates/emptyExample
    - name: replace emptyExample with example_HelloLaser
      run: cp -r ${{ github.workspace }}/addons/ofxLaser/example_HelloLaser ${{ github.workspace }}/examples/templates/emptyExample

    # continue openframeworks defined pipeline
    
    - name: ccache
      uses: hendrikmuhs/ccache-action@v1.2.12
      with:
        key: ${{ matrix.cfg.target }}-${{ matrix.cfg.libs }}

    - name: Download libs
      run: ./scripts/${{matrix.cfg.libs}}/download_libs.sh
    - name: install
      run: ./scripts/ci/$TARGET/install.sh
    - name: Build
      run: ./scripts/ci/$TARGET/build.sh;

      env:
        DEVELOPER_DIR: "/Applications/Xcode_15.2.app/Contents/Developer"
