name: Build Examples

on:
  push:
    paths:
      - ".github/workflows/build-examples.yml"
      - "addon_config.mk"
      - "example_*/**"
      - "libs/**"
      - "scripts/**"
      - "src/**"
  pull_request:
    paths:
      - ".github/workflows/build-examples.yml"
      - "addon_config.mk"
      - "example_*/**"
      - "libs/**"
      - "scripts/**"
      - "src/**"
  workflow_dispatch:

jobs:
  build-examples-macos:
    runs-on: macos-14
    timeout-minutes: 60

    steps:
      - name: Checkout openFrameworks
        uses: actions/checkout@v4
        with:
          repository: openframeworks/openFrameworks
          ref: '0.12.1'
          path: openFrameworks
          submodules: recursive

      - name: Download OF libs
        run: openFrameworks/scripts/osx/download_libs.sh

      - name: Checkout ofxLaser
        uses: actions/checkout@v4
        with:
          path: openFrameworks/addons/ofxLaser
          submodules: recursive

      - name: Build examples
        working-directory: openFrameworks/addons/ofxLaser
        run: ./scripts/build-examples.sh

  build-examples-windows-msys2:
    runs-on: windows-latest
    timeout-minutes: 60

    defaults:
      run:
        shell: msys2 {0}

    steps:
      - name: Checkout openFrameworks
        uses: actions/checkout@v4
        with:
          repository: openframeworks/openFrameworks
          ref: '0.12.1'
          path: openFrameworks
          submodules: recursive

      - name: Checkout ofxLaser
        uses: actions/checkout@v4
        with:
          path: openFrameworks/addons/ofxLaser
          submodules: recursive

      - name: Set up MSYS2
        uses: msys2/setup-msys2@v2.27.0
        with:
          cache: true
          release: true
          update: true
          msystem: ucrt64
          pacboy: >-
            openssl:p
            python:p
            gcc:p
            assimp:p
            cairo:p
            curl:p
            freeglut:p
            freeimage:p
            glew:p
            glfw:p
            glm:p
            fmt:p
            zlib:p
            brotli:p
            libpng:p
            harfbuzz:p
            libsndfile:p
            libusb:p
            libxml2:p
            mpg123:p
            nlohmann-json:p
            openal:p
            opencv:p
            pkgconf:p
            pugixml:p
            rtaudio:p
            uriparser:p
            utf8cpp:p
          install: >-
            unzip
            make

      - name: Download OF MSYS2 libs
        working-directory: openFrameworks
        run: ./scripts/msys2/download_libs.sh --silent -a ucrt64

      - name: Build examples
        working-directory: openFrameworks/addons/ofxLaser
        env:
          BUILD_CORE_TARGET: Debug
          EXAMPLE_TARGET: DebugNoOF
          JOBS: 4
        run: ./scripts/build-examples.sh
